./ldsc.py --h2 sumstats/PASS_AccumbensVol_Satizabal2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_AccumbensVol_Satizabal2019
./ldsc.py --h2 sumstats/PASS_ADHD_Demontis2018.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_ADHD_Demontis2018
./ldsc.py --h2 sumstats/PASS_AgeFirstBirth.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_AgeFirstBirth
./ldsc.py --h2 sumstats/PASS_AgeOfInitiation_Liu2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_AgeOfInitiation_Liu2019
./ldsc.py --h2 sumstats/PASS_Alzheimers_deRojas2021.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Alzheimers_deRojas2021
./ldsc.py --h2 sumstats/PASS_Anorexia.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Anorexia
./ldsc.py --h2 sumstats/PASS_AnorexiaNervosa_Watson2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_AnorexiaNervosa_Watson2019
./ldsc.py --h2 sumstats/PASS_AtrialFibrillation_Nielsen2018.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_AtrialFibrillation_Nielsen2018
./ldsc.py --h2 sumstats/PASS_Autism.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Autism
./ldsc.py --h2 sumstats/PASS_BasoP_Vuckovic2020.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_BasoP_Vuckovic2020
./ldsc.py --h2 sumstats/PASS_BDSCZ_Ruderfer2018.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_BDSCZ_Ruderfer2018
./ldsc.py --h2 sumstats/PASS_BIP_Stahl2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_BIP_Stahl2019
./ldsc.py --h2 sumstats/PASS_BMI1.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_BMI1
./ldsc.py --h2 sumstats/PASS_BrainstemVol_Satizabal2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_BrainstemVol_Satizabal2019
./ldsc.py --h2 sumstats/PASS_CaudateVol_Satizabal2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_CaudateVol_Satizabal2019
./ldsc.py --h2 sumstats/PASS_CigarettesPerDay_Liu2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_CigarettesPerDay_Liu2019
./ldsc.py --h2 sumstats/PASS_DrinksPerWeek_Liu2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_DrinksPerWeek_Liu2019
./ldsc.py --h2 sumstats/PASS_DS.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_DS
./ldsc.py --h2 sumstats/PASS_Eosino_Vuckovic2020.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Eosino_Vuckovic2020
./ldsc.py --h2 sumstats/PASS_Ever_Smoked.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Ever_Smoked
./ldsc.py --h2 sumstats/PASS_GeneralRiskTolerance_KarlssonLinner2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_GeneralRiskTolerance_KarlssonLinner2019
./ldsc.py --h2 sumstats/PASS_Glaucoma_Craig2020.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Glaucoma_Craig2020
./ldsc.py --h2 sumstats/PASS_HDL.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_HDL
./ldsc.py --h2 sumstats/PASS_Height1.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Height1
./ldsc.py --h2 sumstats/PASS_HipOA_Tachmazidou2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_HipOA_Tachmazidou2019
./ldsc.py --h2 sumstats/PASS_IBD_deLange2017.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_IBD_deLange2017
./ldsc.py --h2 sumstats/PASS_Insomnia_Jansen2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Insomnia_Jansen2019
./ldsc.py --h2 sumstats/PASS_Intelligence_SavageJansen2018.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Intelligence_SavageJansen2018
./ldsc.py --h2 sumstats/PASS_IschemicStroke_Malik2018.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_IschemicStroke_Malik2018
./ldsc.py --h2 sumstats/PASS_LDL.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_LDL
./ldsc.py --h2 sumstats/PASS_LymP_Vuckovic2020.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_LymP_Vuckovic2020
./ldsc.py --h2 sumstats/PASS_MCPmale_Johnston2021.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_MCPmale_Johnston2021
./ldsc.py --h2 sumstats/PASS_MDD_Howard2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_MDD_Howard2019
./ldsc.py --h2 sumstats/PASS_MDD_Wray2018.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_MDD_Wray2018
./ldsc.py --h2 sumstats/PASS_MedicationUse_Wu2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_MedicationUse_Wu2019
./ldsc.py --h2 sumstats/PASS_Menarche2017.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Menarche2017
./ldsc.py --h2 sumstats/PASS_MonoP_Vuckovic2020.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_MonoP_Vuckovic2020
./ldsc.py --h2 sumstats/PASS_MO_Zhao2021.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_MO_Zhao2021
./ldsc.py --h2 sumstats/PASS_Myopia_Hysi2020.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Myopia_Hysi2020
./ldsc.py --h2 sumstats/PASS_NumberChildrenEverBorn.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_NumberChildrenEverBorn
./ldsc.py --h2 sumstats/PASS_PancreasVol_Liu2021.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_PancreasVol_Liu2021
./ldsc.py --h2 sumstats/PASS_ProstateCancer.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_ProstateCancer
./ldsc.py --h2 sumstats/PASS_RD_Zhao2021.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_RD_Zhao2021
./ldsc.py --h2 sumstats/PASS_ReactionTime_Davies2018.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_ReactionTime_Davies2018
./ldsc.py --h2 sumstats/PASS_Rheumatoid_Arthritis.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Rheumatoid_Arthritis
./ldsc.py --h2 sumstats/PASS_RTC_Vuckovic2020.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_RTC_Vuckovic2020
./ldsc.py --h2 sumstats/PASS_SA_Grasby2020.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_SA_Grasby2020
./ldsc.py --h2 sumstats/PASS_Schizophrenia_Pardinas2018.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Schizophrenia_Pardinas2018
./ldsc.py --h2 sumstats/PASS_SCZvsBD_Ruderfer2018.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_SCZvsBD_Ruderfer2018
./ldsc.py --h2 sumstats/PASS_SleepDuration_Dashti2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_SleepDuration_Dashti2019
./ldsc.py --h2 sumstats/PASS_SmokingCessation_Liu2019.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_SmokingCessation_Liu2019
./ldsc.py --h2 sumstats/PASS_TH_Grasby2020.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_TH_Grasby2020
./ldsc.py --h2 sumstats/PASS_Type_2_Diabetes.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Type_2_Diabetes
./ldsc.py --h2 sumstats/PASS_Years_of_Education1.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Years_of_Education1
./ldsc.py --h2 sumstats/PASS_Years_of_Education2.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/PASS_Years_of_Education2
./ldsc.py --h2 sumstats/UKB_460K.biochemistry_AlkalinePhosphatase.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.biochemistry_AlkalinePhosphatase
./ldsc.py --h2 sumstats/UKB_460K.biochemistry_AspartateAminotransferase.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.biochemistry_AspartateAminotransferase
./ldsc.py --h2 sumstats/UKB_460K.biochemistry_Cholesterol.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.biochemistry_Cholesterol
./ldsc.py --h2 sumstats/UKB_460K.biochemistry_Creatinine.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.biochemistry_Creatinine
./ldsc.py --h2 sumstats/UKB_460K.biochemistry_IGF1.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.biochemistry_IGF1
./ldsc.py --h2 sumstats/UKB_460K.biochemistry_Phosphate.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.biochemistry_Phosphate
./ldsc.py --h2 sumstats/UKB_460K.biochemistry_Testosterone_Male.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.biochemistry_Testosterone_Male
./ldsc.py --h2 sumstats/UKB_460K.biochemistry_TotalBilirubin.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.biochemistry_TotalBilirubin
./ldsc.py --h2 sumstats/UKB_460K.biochemistry_TotalProtein.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.biochemistry_TotalProtein
./ldsc.py --h2 sumstats/UKB_460K.biochemistry_VitaminD.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.biochemistry_VitaminD
./ldsc.py --h2 sumstats/UKB_460K.blood_PLATELET_COUNT.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.blood_PLATELET_COUNT
./ldsc.py --h2 sumstats/UKB_460K.blood_RBC_DISTRIB_WIDTH.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.blood_RBC_DISTRIB_WIDTH
./ldsc.py --h2 sumstats/UKB_460K.blood_RED_COUNT.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.blood_RED_COUNT
./ldsc.py --h2 sumstats/UKB_460K.blood_WHITE_COUNT.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.blood_WHITE_COUNT
./ldsc.py --h2 sumstats/UKB_460K.bmd_HEEL_TSCOREz.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.bmd_HEEL_TSCOREz
./ldsc.py --h2 sumstats/UKB_460K.body_BALDING1.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.body_BALDING1
./ldsc.py --h2 sumstats/UKB_460K.body_BMIz.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.body_BMIz
./ldsc.py --h2 sumstats/UKB_460K.body_HEIGHTz.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.body_HEIGHTz
./ldsc.py --h2 sumstats/UKB_460K.body_WHRadjBMIz.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.body_WHRadjBMIz
./ldsc.py --h2 sumstats/UKB_460K.bp_DIASTOLICadjMEDz.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.bp_DIASTOLICadjMEDz
./ldsc.py --h2 sumstats/UKB_460K.cancer_BREAST.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.cancer_BREAST
./ldsc.py --h2 sumstats/UKB_460K.cancer_PROSTATE.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.cancer_PROSTATE
./ldsc.py --h2 sumstats/UKB_460K.cov_EDU_YEARS.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.cov_EDU_YEARS
./ldsc.py --h2 sumstats/UKB_460K.disease_ALLERGY_ECZEMA_DIAGNOSED.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.disease_ALLERGY_ECZEMA_DIAGNOSED
./ldsc.py --h2 sumstats/UKB_460K.disease_HYPOTHYROIDISM_SELF_REP.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.disease_HYPOTHYROIDISM_SELF_REP
./ldsc.py --h2 sumstats/UKB_460K.lung_FEV1FVCzSMOKE.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.lung_FEV1FVCzSMOKE
./ldsc.py --h2 sumstats/UKB_460K.lung_FVCzSMOKE.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.lung_FVCzSMOKE
./ldsc.py --h2 sumstats/UKB_460K.mental_NEUROTICISM.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.mental_NEUROTICISM
./ldsc.py --h2 sumstats/UKB_460K.other_MORNINGPERSON.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.other_MORNINGPERSON
./ldsc.py --h2 sumstats/UKB_460K.pigment_SUNBURN.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.pigment_SUNBURN
./ldsc.py --h2 sumstats/UKB_460K.repro_AgeFirstBirth_Female.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.repro_AgeFirstBirth_Female
./ldsc.py --h2 sumstats/UKB_460K.repro_MENARCHE_AGE.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.repro_MENARCHE_AGE
./ldsc.py --h2 sumstats/UKB_460K.repro_MENOPAUSE_AGE.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.repro_MENOPAUSE_AGE
./ldsc.py --h2 sumstats/UKB_460K.repro_NumberChildrenEverBorn_Pooled.sumstats.gz --ref-ld-chr eur_w_ld_chr_ben/ --w-ld-chr eur_w_ld_chr_ben/ --out output_ben/UKB_460K.repro_NumberChildrenEverBorn_Pooled
